[build]
  command = "echo 'No build step needed'"
  publish = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://3lzb91e0fe.execute-api.us-east-2.amazonaws.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
